### ISSUE TITLE
Doesn't work anymore Pt2

### ISSUE THREAD

**Issue by codingyourlife** [deconf/Google-Analytics-Dashboard-for-WP#54] opened 2016-01-23 12:35 UTC
Related to this topic: https://github.com/deconf/Google-Analytics-Dashboard-for-WP/issues/53#issuecomment-171567171

I contacted my host and they told me to enter:
/** GADWP force Internet Protocol version */
define('GADWP_IP_VERSION', 1);

At the end of wp-config.php. But now I get this error:
Last Error: 2016-01-23 12:30:19: exception 'Google_IO_Exception' with message 'couldn't connect to host' in /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/IO/Curl.php:86
Stack trace:
#0 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/IO/Abstract.php(135): Google_IO_Curl->executeRequest(Object(Google_Http_Request))
#1 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/Auth/OAuth2.php(113): Google_IO_Abstract->makeRequest(Object(Google_Http_Request))
#2 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/tools/src/Google/Client.php(133): Google_Auth_OAuth2->authenticate('[CENSORED]...')
#3 /home/.sites/97/site1310/web/sites/blog/wp-content/plugins/google-analytics-dashboard-for-wp/admin/settings.php(739): Google_Client->authenticate('[CENSORED]...')
#4 [internal function]: GADWP_Settings::general_settings('')
#5 /home/.sites/97/site1310/web/sites/blog/wp-includes/plugin.php(525): call_user_func_array(Array, Array)
#6 /home/.sites/97/site1310/web/sites/blog/wp-admin/admin.php(236): do_action('toplevel_page_g...')
#7 {main}

Still a hoster problem?

**Comment by deconf** [comment] 2016-01-23 16:07
Yes, it's a hoster issue. For some reason PHP cURL can't connect to www.googleapis.com. They should drive some tests on that server and identify the exact issue.

Since support takes place on https://wordpress.org/support/plugin/google-analytics-dashboard-for-wp and this is not a bug, i'm closing this issue.

**Closed by deconf** 2016-01-23 16:07 UTC
